[project]
name = "parsec"
version = "3.17.0"
description = "parser combinator."
readme = "README.md"
authors = [
    { name = "He Tao", email = "sighingnow@gmail.com" },
]
requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/sighingnow/parsec.py"

[project.optional-dependencies]
type-check = [
  "mypy ~= 2.3.0",
]
dev = [
  "parsec[type-check]",
]
all = [
  "parsec[dev]",
]

[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.mypy]
install_types = true
ignore_missing_imports = true
check_untyped_defs = true

