#!/usr/bin/env python
# -*- coding: utf-8 -*-

import collections as C
import collections.abc as CA
import re
import typing as T

_U = T.TypeVar('_U', covariant=True)
_V = T.TypeVar('_V')
_VS = T.TypeVar('_VS', bound=CA.Sequence)

_Ts = T.TypeVarTuple("_Ts")

_LocInfo = tuple[int, int]

CH = T.TypeVar('CH')
Text = CA.Sequence["CH"]

class ParseError(RuntimeError):
    expected: str
    text: Text
    index: int
    def __init__(self, expected: str, text: Text, index: int) -> None: ...
    @staticmethod
    def loc_info(text: Text, index: int) -> _LocInfo: ...
    def loc(self) -> str: ...
    def __str__(self) -> str: ...

class Value(C.namedtuple('Value', 'status index value expected'), T.Generic[_U]):
    @staticmethod
    def success(index: int, actual: _V) -> Value[_V]: ...
    @staticmethod
    def failure(index: int, expected: str) -> Value[_U]: ...
    def aggregate(
        self: Value[CA.Sequence[_V]], other: T.Optional[Value[CA.Sequence[_V]]] = ...
    ) -> Value[CA.Sequence[_V]]: ...
    def update_index(self, index: T.Optional[int] = None) -> Value[_U]: ...
    @staticmethod
    def combinate(values: CA.Iterable[Value[_V]]) -> Value[tuple[_V, ...]]: ...
    def __str__(self) -> str: ...

class Parser(T.Generic[_U]):
    def __init__(self, fn: CA.Callable[[Text, int], Value[_U]]) -> None: ...
    def __call__(self, text: Text, index: int) -> Value[_U]: ...
    def parse(self, text: Text) -> _U: ...
    def parse_partial(self, text: Text) -> tuple[_U, Text]: ...
    def parse_strict(self, text: Text) -> _U: ...
    @T.overload
    def bind(self, fn: CA.Callable[[_U], Parser[_V]]) -> Parser[_V]: ...
    @T.overload
    def bind(self, fn: CA.Callable[[_U, int], Parser[_V]]) -> Parser[_V]: ...
    def compose(self, other: Parser[_V]) -> Parser[_V]: ...
    @T.overload
    def joint[A](self, a: Parser[A]) -> Parser[tuple[_U, A]]: ...
    @T.overload
    def joint[A, B](self, a: Parser[A], b: Parser[B]) -> Parser[tuple[_U, A, B]]: ...
    @T.overload
    def joint[A, B, C](self, a: Parser[A], b: Parser[B], c: Parser[C]) -> Parser[tuple[_U, A, B, C]]: ...
    @T.overload
    def joint[A, B, C, D](self, a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D]) -> Parser[tuple[_U, A, B, C, D]]: ...
    @T.overload
    def joint[A, B, C, D, E](self, a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E]) -> Parser[tuple[_U, A, B, C, D, E]]: ...
    @T.overload
    def joint[A, B, C, D, E, F](self, a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E], f: Parser[F]) -> Parser[tuple[_U, A, B, C, D, E, F]]: ...
    @T.overload
    def joint(self, *parsers: Parser[_U]) -> Parser[tuple[_U, ...]]: ...
    def choice(self, other: Parser[_U]) -> Parser[_U]: ...
    def try_choice(self, other: Parser[_U]) -> Parser[_U]: ...
    def skip(self, other: Parser[_V]) -> Parser[_U]: ...
    def ends_with(self, other: Parser[_V]) -> Parser[_U]: ...
    def excepts(self, ohter: Parser[_V]) -> Parser[_U]: ...
    @T.overload
    def parsecmap(self, fn: CA.Callable[[_U, *_Ts], _V], star: T.Literal[True]) -> Parser[_V]: ...
    @T.overload
    def parsecmap(self, fn: CA.Callable[[_U], _V], star: T.Literal[False]) -> Parser[_V]: ...
    @T.overload
    def parsecmap(self, fn: CA.Callable[[*_Ts], _V], star: bool = False) -> Parser[_V]: ...
    @T.overload
    def map(self: Parser[tuple[*_Ts]], fn: CA.Callable[[*_Ts], _V], star: T.Literal[True]) -> Parser[_V]: ...
    @T.overload
    def map(self, fn: CA.Callable[[_U], _V], star: T.Literal[False]) -> Parser[_V]: ...
    @T.overload
    def map(self, fn: CA.Callable[[_U], _V], star: bool = False) -> Parser[_V]: ...
    def parsecapp(
        self: Parser[CA.Callable[[_U, *_Ts], _V]], other: Parser[tuple[*_Ts]]
    ) -> Parser[_V]: ...
    def apply(
        self: Parser[CA.Callable[[_U, *_Ts], _V]], other: Parser[tuple[*_Ts]]
    ) -> Parser[_V]: ...
    def result(self, res: _V) -> Parser[_V]: ...
    def mark(self) -> Parser[tuple[_LocInfo, _U, _LocInfo]]: ...
    def desc(self, description: str) -> Parser[_U]: ...
    def __or__(self, other: Parser[_U]) -> Parser[_U]: ...
    def __xor__(self, other: Parser[_U]) -> Parser[_U]: ...
    def __add__(self, other: Parser[_V]) -> Parser[tuple[_U, _V]]: ...
    def __rshift__(self, other: Parser[_V]) -> Parser[_V]: ...
    def __gt__(self, other: Parser[_V]) -> Parser[_V]: ...
    def __irshift__(self: Parser[tuple[_U, *_Ts]], other: CA.Callable[[_U, *_Ts], Parser[_V]]) -> Parser[_V]: ... # type: ignore[misc]
    def __ge__(self, other: Parser[_V]) -> Parser[_V]: ...
    def __lshift__(self, other: Parser[_V]) -> Parser[_U]: ...
    def __lt__(self, other: Parser[_V]) -> Parser[_U]: ...
    def __truediv__(self, other: Parser[_V]) -> Parser[_U]: ...

def parse(p: Parser[_V], text: Text, index: int) -> _V: ...
@T.overload
def bind(p: Parser[_U], fn: CA.Callable[[_U], Parser[_V]]) -> Parser[_V]: ...
@T.overload
def bind(p: Parser[_U], fn: CA.Callable[[_U, int], Parser[_V]]) -> Parser[_V]: ...
def compose(pa: Parser, pb: Parser[_V]) -> Parser[_V]: ...
@T.overload
def joint[A](a: Parser[A]) -> Parser[tuple[A]]: ...
@T.overload
def joint[A, B](a: Parser[A], b: Parser[B]) -> Parser[tuple[A, B]]: ...
@T.overload
def joint[A, B, C](a: Parser[A], b: Parser[B], c: Parser[C]) -> Parser[tuple[A, B, C]]: ...
@T.overload
def joint[A, B, C, D](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D]) -> Parser[tuple[A, B, C, D]]: ...
@T.overload
def joint[A, B, C, D, E](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E]) -> Parser[tuple[A, B, C, D, E]]: ...
@T.overload
def joint[A, B, C, D, E, F](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E], f: Parser[F]) -> Parser[tuple[A, B, C, D, E, F]]: ...
@T.overload
def joint[T](*args: Parser[T]) -> Parser[T]: ...
def choice(pa: Parser[_U], pb: Parser[_U]) -> Parser[_U]: ...
def try_choice(pa: Parser[_U], pb: Parser[_U]) -> Parser[_U]: ...
@T.overload
def try_choices[A](a: Parser[A]) -> Parser[T.Union[A]]: ...
@T.overload
def try_choices[A, B](a: Parser[A], b: Parser[B]) -> Parser[T.Union[A, B]]: ...
@T.overload
def try_choices[A, B, C](a: Parser[A], b: Parser[B], c: Parser[C]) -> Parser[T.Union[A, B, C]]: ...
@T.overload
def try_choices[A, B, C, D](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D]) -> Parser[T.Union[A, B, C, D]]: ...
@T.overload
def try_choices[A, B, C, D, E](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E]) -> Parser[T.Union[A, B, C, D, E]]: ...
@T.overload
def try_choices[A, B, C, D, E, F](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E], f: Parser[F]) -> Parser[T.Union[A, B, C, D, E, F]]: ...
@T.overload
def try_choices[T](*args: Parser[T]) -> Parser[T]: ...
@T.overload
def try_choices_longest[A](a: Parser[A]) -> Parser[T.Union[A]]: ...
@T.overload
def try_choices_longest[A, B](a: Parser[A], b: Parser[B]) -> Parser[T.Union[A, B]]: ...
@T.overload
def try_choices_longest[A, B, C](a: Parser[A], b: Parser[B], c: Parser[C]) -> Parser[T.Union[A, B, C]]: ...
@T.overload
def try_choices_longest[A, B, C, D](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D]) -> Parser[T.Union[A, B, C, D]]: ...
@T.overload
def try_choices_longest[A, B, C, D, E](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E]) -> Parser[T.Union[A, B, C, D, E]]: ...
@T.overload
def try_choices_longest[A, B, C, D, E, F](a: Parser[A], b: Parser[B], c: Parser[C], d: Parser[D], e: Parser[E], f: Parser[F]) -> Parser[T.Union[A, B, C, D, E, F]]: ...
@T.overload
def try_choices_longest[T](*args: Parser[T]) -> Parser[T]: ...
def skip(pa: Parser[_U], pb: Parser) -> Parser[_U]: ...
def ends_with(pa: Parser[_U], pb: Parser) -> Parser[_U]: ...
def excepts(pa: Parser[_U], pb: Parser) -> Parser[_U]: ...
def parsecmap(p: Parser[_U], fn: CA.Callable[[_U], _V]) -> Parser[_V]: ...
def parsecapp(p: Parser[CA.Callable[[_U], _V]], other: Parser[_U]) -> Parser[_V]: ...
def result(p: Parser, res: _V) -> Parser[_V]: ...
def mark(p: Parser[_U]) -> Parser[tuple[_LocInfo, _U, _LocInfo]]: ...
def desc(p: Parser[_U], description: str) -> Parser[_U]: ...
@T.overload
def generate(
    fn: str,
) -> CA.Callable[
    [CA.Callable[[], CA.Generator[Parser[_U], _U, Parser[_V] | _V]]], Parser[_V]
]: ...
@T.overload
def generate(
    fn: CA.Callable[[], CA.Generator[Parser[_U], _U, Parser[_V] | _V]]
) -> Parser[_V]: ...
def times(
    p: Parser[_U], mint: int, maxt: T.Optional[float] = ...
) -> Parser[CA.Sequence[_U]]: ...
def count(p: Parser[_U], n: int) -> Parser[CA.Sequence[_U]]: ...

@T.overload
def optional(p: Parser[_U], default_value: None = None) -> Parser[_U | None]: ...
@T.overload
# NOTE: Reuses _U to leverage type inferencing widening
def optional(p: Parser[_V], default_value: _V) -> Parser[_V]: ...

def many(p: Parser[_U]) -> Parser[CA.Sequence[_U]]: ...
def many1(p: Parser[_U]) -> Parser[CA.Sequence[_U]]: ...
def separated(
    p: Parser[_U],
    sep: Parser,
    mint: int,
    maxt: T.Optional[int] = ...,
    end: T.Optional[bool] = ...,
) -> Parser[CA.Sequence[_U]]: ...
def sepBy(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def sepBy1(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def endBy(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def endBy1(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def sepEndBy(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def sepEndBy1(p: Parser[_U], sep: Parser) -> Parser[CA.Sequence[_U]]: ...
def satisfy(predicate: CA.Callable[[_U], bool]) -> Parser[_U]: ...
def any() -> Parser: ...
def one_of(s: CA.Container[_U]) -> Parser[_U]: ...
def none_of(s: CA.Container[_U]) -> Parser[_U]: ...
def space() -> Parser[str]: ...
def spaces() -> Parser[CA.Sequence[str]]: ...
def letter() -> Parser[str]: ...
def digit() -> Parser[str]: ...
def eof() -> Parser[None]: ...
def string(s: _VS) -> Parser[_VS]: ...
def regex(exp: str | re.Pattern, flags: re.RegexFlag = ...) -> Parser[str]: ...
def newline() -> Parser[str]: ...
def crlf() -> Parser[str]: ...
def end_of_line() -> Parser[str]: ...
def success_with(value: _V, advance: bool = False) -> Parser[_V]: ...
def fail_with(message: str) -> Parser[T.Never]: ...
def exclude(p: Parser[_U], exclude: Parser) -> Parser[_U]: ...
def lookahead(p: Parser[_U]) -> Parser[_U]: ...
def unit(p: Parser[_U]) -> Parser[_U]: ...
def between(open: Parser, close: Parser, parser: Parser[_U]) -> Parser[_U]: ...
def validate(predicate: CA.Callable[[_U], bool]) -> Parser[_U]: ...

sign: Parser[CA.Callable[[_U], _U]]

def number(base: int, digit: Parser[str]) -> Parser[int]: ...

binary_digit: Parser[str]
binary_number: Parser[int]
binary: Parser[int]

octal_digit: Parser[str]
octal_number: Parser[int]
octal: Parser[int]

hexadecimal_digit: Parser[str]
hexadecimal_number: Parser[int]
hexadecimal: Parser[int]

decimal_number: Parser[int]
decimal: Parser[int]

zero_number: Parser[int]
natural: Parser[int]
integer: Parser[int]

if T.TYPE_CHECKING:
    import dataclasses as D

    # Ensure that U in Parser[U] is covariant
    class _Base(T.Protocol):
        @property
        def value(self) -> str: ...

    @D.dataclass(frozen=True)
    class _A(_Base):
        value: str

    @D.dataclass(frozen=True)
    class _B(_Base):
        value: str

    _a = string("a").map(lambda value: _A(value))
    T.assert_type(_a, Parser[_A])

    _b = string("b").map(lambda value: _B(value))
    T.assert_type(_b, Parser[_B])

    _inferred = try_choices_longest(_a, _b)
    T.assert_type(_inferred, Parser[_A | _B])

    _base: Parser[_Base] = _inferred

    # Ensure Literal does not decay to with literal string default in optional()
    _Literal = T.Literal["foo", "bar"]

    _literal: Parser[_Literal] = try_choices_longest(
        *(string(literal) for literal in T.get_args(_Literal)),
    )

    _literal_with_default: Parser[_Literal] = optional(_literal, "bar")

    # Ensure optional[_U]() can implicitly widen _U
    _widened: Parser[_Literal | T.Literal["123"]] = optional(_literal, "123")
